services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      DB_PATH: /opt/inventory/data/inventory.db
    volumes:
      - ./data:/opt/inventory/data
      - ./backups:/opt/inventory/backups
